#!/bin/bash

me=`basename $0`

info="${me}[$(hostname)]:"

arg=${1}

#****************************************************************************

cpu0_drv=/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver
cpu_drv_glob=/sys/devices/system/cpu/cpu*/cpufreq/scaling_driver

cpu_gov=/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
cpu_gov_glob=/sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

#****************************************************************************

info_drv="<unknown>"
if test -r ${cpu0_drv} ; then
    info_drv=$( cat ${cpu_drv_glob} | uniq )
fi

info_gov="<unknown>"
if test -r ${cpu0_gov} ; then
    info_gov=$( cat ${cpu_gov_glob} | uniq )
fi

info_freq=$( lscpu | grep "CPU MHz" | sed -e 's/   */ /' )

is_node_0=no
if [[ "${SLURM_NODEID}" = "0" || "${PBS_NODENUM}" = "0" ]] ; then
    is_node_0=yes
fi

printf "${info} CPU scaling driver: '${info_drv}'; governor: '${info_gov}'; ${info_freq}\n"

if [[ ${arg} =~ --all || "${is_node_0}" = "yes" ]] ; then
    printf "${info} CPU info:\n" && \
	cat /proc/cpuinfo | grep "model name" | uniq && \
	lscpu
fi
