#!/bin/bash

me=`basename $0`

hostname=`hostname`

for b in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor ; do
    echo ondemand  > $b;
done

printf "${me}: ${hostname}: restoring CPU 'dynamic turbo'. Governor says: " && \
    cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor | uniq
