#!/bin/bash

#****************************************************************************
# $HeadURL$
# $Id$
#
# Ryan Friese, Nathan Tallent
#****************************************************************************

me=`basename $0`

info="${me}[$(hostname)]:"

#****************************************************************************

sys_cpu_gov=/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
sysglob_cpu_gov=/sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

#****************************************************************************

if [[ ! -w "${sys_cpu_gov}" ]] ; then
    echo "*** Error: ${info} Cannot write '${sys_cpu_gov}'!"
    exit 1
fi

for x in ${sysglob_cpu_gov} ; do
    echo ondemand > $x;
done

#****************************************************************************

info_gov=$( cat ${sysglob_cpu_gov} | uniq )

printf "${info} restoring CPU 'dynamic turbo'. Governor: ${info_gov}\n"
